name = "SARProcessing"
uuid = "f3128dc3-44ca-4ad6-8356-fc70777d194e"
authors = ["lupemba "]
version = "0.1.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"

[compat]
ArchGDAL = "0.9"
Images = "0.25"
XMLDict = "0.4"
